# Generated by Django 4.0 on 2021-12-31 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=3)),
                ('city', models.CharField(default=None, max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='destination',
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='flight',
            name='destinations',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flights.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flights.airport'),
        ),
    ]
